name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Enable LeetCode Plugin
          plugin_leetcode: yes
          plugin_leetcode_user: shridhar024
          plugin_leetcode_sections: solved, calendar
